MyFacultyWebApplication/MyFacultyWebApplication/Models/Material.cs
<<<<<<< HEAD
﻿using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
=======
﻿using System.ComponentModel.DataAnnotations;
>>>>>>> 59fc604a407e294acf4cfcaf8766e2accc31f2f6

namespace MyFacultyWebApplication.Models;

public partial class Material
{
    
    public int Id { get; set; }
    [Required(ErrorMessage = "Поле не повинно бути порожнім")]
    [Display(Name = "Назва")]
    public string Name { get; set; } = null!;
    [Required(ErrorMessage = "Поле не повинно бути порожнім")]
    [Display(Name = "Посилання")]
    public string Url { get; set; } = null!;
    [Required(ErrorMessage = "Поле не повинно бути порожнім")]
    [Display(Name = "Предмет")]
    public int SubjectId { get; set; }

    public virtual Subject Subject { get; set; } = null!;
}

MyFacultyWebApplication/MyFacultyWebApplication/Controllers/MaterialsController.cs
<<<<<<< HEAD
﻿using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
=======
﻿using Microsoft.AspNetCore.Mvc;
>>>>>>> 59fc604a407e294acf4cfcaf8766e2accc31f2f6
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyFacultyWebApplication.Models;

namespace MyFacultyWebApplication.Controllers
{
<<<<<<< HEAD
    [Authorize(Roles = "admin")]
=======
>>>>>>> 59fc604a407e294acf4cfcaf8766e2accc31f2f6
    public class MaterialsController : Controller
    {
        private readonly MyFacultyDbContext _context;

        public MaterialsController(MyFacultyDbContext context)
        {
            _context = context;
        }

        // GET: Materials
        public async Task<IActionResult> Index()
        {
<<<<<<< HEAD
            var materials = _context.Materials.Include(m => m.Subject);
            return View(await materials.ToListAsync());
=======
            var myFacultyDbContext = _context.Materials.Include(m => m.Subject);
            return View(await myFacultyDbContext.ToListAsync());
>>>>>>> 59fc604a407e294acf4cfcaf8766e2accc31f2f6
        }

        // GET: Materials/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Materials == null)
            {
                return NotFound();
            }

            var material = await _context.Materials
                .Include(m => m.Subject)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (material == null)
            {
                return NotFound();
            }

            return View(material);
        }

        // GET: Materials/Create
<<<<<<< HEAD
        public IActionResult Create(int subjectId = -1)
        {
            if (subjectId == -1)
            {
                ViewData["AddToSubject"] = false;
                ViewData["SubjectList"] = new SelectList(_context.Subjects, "Id", "Abbreviation");
                return View();
            }
            ViewData["AddToSubject"] = true;
            ViewData["SubjectId"] = subjectId;
            return View();
        }


=======
        public IActionResult Create()
        {
            ViewData["SubjectId"] = new SelectList(_context.Subjects, "Id", "Abbreviation");
            return View();
        }

>>>>>>> 59fc604a407e294acf4cfcaf8766e2accc31f2f6
        // POST: Materials/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Url,SubjectId")] Material material)
        {
<<<<<<< HEAD
            material.Subject = await _context.Subjects.SingleAsync(s => s.Id == material.SubjectId);

=======
>>>>>>> 59fc604a407e294acf4cfcaf8766e2accc31f2f6
            if (ModelState.IsValid)
            {
                _context.Add(material);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["SubjectId"] = new SelectList(_context.Subjects, "Id", "Abbreviation", material.SubjectId);
            return View(material);
        }

        // GET: Materials/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Materials == null)
            {
                return NotFound();
            }

            var material = await _context.Materials.FindAsync(id);
            if (material == null)
            {
                return NotFound();
            }
            ViewData["SubjectId"] = new SelectList(_context.Subjects, "Id", "Abbreviation", material.SubjectId);
            return View(material);
        }

        // POST: Materials/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Url,SubjectId")] Material material)
        {
            if (id != material.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(material);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MaterialExists(material.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["SubjectId"] = new SelectList(_context.Subjects, "Id", "Abbreviation", material.SubjectId);
            return View(material);
        }

        // GET: Materials/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Materials == null)
            {
                return NotFound();
            }

            var material = await _context.Materials
                .Include(m => m.Subject)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (material == null)
            {
                return NotFound();
            }

            return View(material);
        }

        // POST: Materials/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Materials == null)
            {
                return Problem("Entity set 'MyFacultyDbContext.Materials'  is null.");
            }
            var material = await _context.Materials.FindAsync(id);
            if (material != null)
            {
                _context.Materials.Remove(material);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MaterialExists(int id)
        {
            return (_context.Materials?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

MyFacultyWebApplication/MyFacultyWebApplication/Controllers/SubjectsController.cs
<<<<<<< HEAD
﻿using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyFacultyWebApplication;
=======
﻿using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
>>>>>>> 59fc604a407e294acf4cfcaf8766e2accc31f2f6
using MyFacultyWebApplication.Models;

namespace MyFacultyWebApplication.Controllers
{
    public class SubjectsController : Controller
    {
        private readonly MyFacultyDbContext _context;

        public SubjectsController(MyFacultyDbContext context)
        {
            _context = context;
        }

        // GET: Subjects
        public async Task<IActionResult> Index()
        {
<<<<<<< HEAD
              return _context.Subjects != null ? 
                          View(await _context.Subjects.ToListAsync()) :
                          Problem("Entity set 'MyFacultyDbContext.Subjects'  is null.");
=======
            return _context.Subjects != null ?
                        View(await _context.Subjects.ToListAsync()) :
                        Problem("Entity set 'MyFacultyDbContext.Subjects'  is null.");
>>>>>>> 59fc604a407e294acf4cfcaf8766e2accc31f2f6
        }

        // GET: Subjects/Details/5
        public async Task<IActionResult> Details(int? id)
        {
<<<<<<< HEAD
            if (id == null || _context.Subjects == null) return NotFound();

            var subject = await _context.Subjects.FirstOrDefaultAsync(m => m.Id == id);

            if (subject == null) return NotFound();

            ViewBag.Teachers = await _context.TeacherToSubjectRelations.Where(m => m.SubjectId == id).Select(g => g.Teacher).ToListAsync();
            ViewBag.Materials = await _context.Materials.Where(m => m.SubjectId == id).ToListAsync();
=======
            if (id == null || _context.Subjects == null)
            {
                return NotFound();
            }

            var subject = await _context.Subjects
                .FirstOrDefaultAsync(s => s.Id == id);

            ViewBag.Materials = _context.Materials.Where(m => m.SubjectId == id);
            var TeachersId = _context.TeacherToSubjectRelations.Where(m => m.SubjectId == id).Select(m => m.TeacherId);
            ViewBag.Teachers = _context.Teachers.Where(m => TeachersId.Contains(m.Id));
            if (subject == null)
            {
                return NotFound();
            }
>>>>>>> 59fc604a407e294acf4cfcaf8766e2accc31f2f6

            return View(subject);
        }

        // GET: Subjects/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Subjects/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,NumberOfHours,Abbreviation")] Subject subject)
        {
            if (ModelState.IsValid)
            {
                _context.Add(subject);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(subject);
        }

        // GET: Subjects/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Subjects == null)
            {
                return NotFound();
            }

            var subject = await _context.Subjects.FindAsync(id);
            if (subject == null)
            {
                return NotFound();
            }
            return View(subject);
        }

        // POST: Subjects/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,NumberOfHours,Abbreviation")] Subject subject)
        {
            if (id != subject.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(subject);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SubjectExists(subject.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(subject);
        }

        // GET: Subjects/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Subjects == null)
            {
                return NotFound();
            }

            var subject = await _context.Subjects
                .FirstOrDefaultAsync(m => m.Id == id);
            if (subject == null)
            {
                return NotFound();
            }

            return View(subject);
        }

        // POST: Subjects/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Subjects == null)
            {
                return Problem("Entity set 'MyFacultyDbContext.Subjects'  is null.");
            }
            var subject = await _context.Subjects.FindAsync(id);
            if (subject != null)
            {
                _context.Subjects.Remove(subject);
            }
<<<<<<< HEAD
            
=======

>>>>>>> 59fc604a407e294acf4cfcaf8766e2accc31f2f6
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SubjectExists(int id)
        {
<<<<<<< HEAD
          return (_context.Subjects?.Any(e => e.Id == id)).GetValueOrDefault();
=======
            return (_context.Subjects?.Any(e => e.Id == id)).GetValueOrDefault();
>>>>>>> 59fc604a407e294acf4cfcaf8766e2accc31f2f6
        }
    }
}

MyFacultyWebApplication/MyFacultyWebApplication/Views/Materials/Create.cshtml
@model MyFacultyWebApplication.Models.Material

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Material</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Url" class="control-label"></label>
                <input asp-for="Url" class="form-control" />
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>
<<<<<<< HEAD

            @{
                if(ViewBag.AddToSubject)
                {
                        <input type="hidden" value="@ViewBag.SubjectId" name= "SubjectId" />
                }
                else
                {
                    <div class="form-group">
                        <label asp-for="SubjectId" class="control-label"></label>
                        <select asp-for="SubjectId" class ="form-control" asp-items="ViewBag.SubjectList"></select>
                    </div>
                }
            }
            
            
            <hr/>
=======
            <div class="form-group">
                <label asp-for="SubjectId" class="control-label"></label>
                <select asp-for="SubjectId" class ="form-control" asp-items="ViewBag.SubjectId"></select>
            </div>
>>>>>>> 59fc604a407e294acf4cfcaf8766e2accc31f2f6
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
<<<<<<< HEAD
    @{
        if (ViewBag.AddToSubject)
        {
            <a asp-controller="Subjects" asp-action="Details" asp-route-id="@ViewBag.SubjectId">Back to Subject</a>
        }
        else
        {
            <a asp-action="Index">Back to List</a>
        }
    }
=======
    <a asp-action="Index">Back to List</a>
>>>>>>> 59fc604a407e294acf4cfcaf8766e2accc31f2f6
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
<<<<<<< HEAD
}
=======
}
>>>>>>> 59fc604a407e294acf4cfcaf8766e2accc31f2f6

MyFacultyWebApplication/MyFacultyWebApplication/Views/Materials/Delete.cshtml
@model MyFacultyWebApplication.Models.Material

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Material</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Url)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Url)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subject.Abbreviation)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MyFacultyWebApplication/MyFacultyWebApplication/Views/Materials/Details.cshtml
@model MyFacultyWebApplication.Models.Material

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Material</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Url)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Url)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Subject)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Subject.Abbreviation)
        </dd>
    </dl>
</div>
<<<<<<< HEAD
=======

<div>
    <h1>Матеріали з предмету @ViewBag.SubjectName</h1>

    <p>
        <a asp-action="Create" asp-route-id="@ViewBag.MaterialId">Додати новий матеріал</a>
    </p>
</div>

>>>>>>> 59fc604a407e294acf4cfcaf8766e2accc31f2f6
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MyFacultyWebApplication/MyFacultyWebApplication/Views/Materials/Edit.cshtml
@model MyFacultyWebApplication.Models.Material

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Material</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Url" class="control-label"></label>
                <input asp-for="Url" class="form-control" />
                <span asp-validation-for="Url" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SubjectId" class="control-label"></label>
                <select asp-for="SubjectId" class="form-control" asp-items="ViewBag.SubjectId"></select>
                <span asp-validation-for="SubjectId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MyFacultyWebApplication/MyFacultyWebApplication/Views/Materials/Index.cshtml
@model IEnumerable<MyFacultyWebApplication.Models.Material>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Url)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Subject)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Url)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Subject.Abbreviation)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>